Added when/if
cspotcode/ManicMinersScripting pull request #2
Opened 2020-09-23 18:15 UTC by Akorax

Just testing the function of proposing changes.

2020-09-23 18:18 UTC, cspotcode commented on .vscode/manic-miners.code-snippets
> +		"scope": "javascript,typescript",
As discussed on Discord, we'll need to remove these "scope" entries.  Eventually we can have a "manicminerslevel" language which can go here.

I know you already know this, but putting a comment shows how we can discuss changes on github.

2020-09-23 20:41 UTC, cspotcode requested changes
I think I found a typo.  Also made a suggestion about some descriptions.  I technically didn't look at *all* of it, but this looks like a great start.

2020-09-23 20:41 UTC, cspotcode commented on .vscode/manic-miners.code-snippets
> +		"description": "Writes If and put the cursor inside the parenthesis."
Should we update these descriptions to focus on the meaning of `When` and `If`, to help the scripter understand what they're doing?

2020-09-23 20:41 UTC, cspotcode commented on .vscode/manic-miners.code-snippets
> +		"body": "time:${1:row},${2:column}",
update placeholders to get rid of row, column.

2020-09-23 20:47 UTC, Akorax commented on .vscode/manic-miners.code-snippets
> +		"description": "Writes If and put the cursor inside the parenthesis."
I think very few will look at the descriptions. If they do they probably do it on the wiki where the most updated info is.

2020-09-23 20:48 UTC, cspotcode commented on .vscode/manic-miners.code-snippets
> +		"description": "Writes If and put the cursor inside the parenthesis."
That's fair, but these descriptions are still inconsistent with the others.  This one describes what is being typed, whereas the others focus on what the code means in the game.

2020-09-25 19:09 UTC, cspotcode commented
These changes have been incorporated via https://github.com/cspotcode/ManicMinersScripting/blob/master/vscode-extension/generate-code-snippets.js

2020-09-25 19:09 UTC, closed without merging